import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/redux/reduxProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    suppressHydrationWarning >
      <body className="min-h-full flex flex-col" suppressHydrationWarning><ReduxProvider> {children} </ReduxProvider></body>
    </html>
  );
}
